### ISSUE TITLE
Mov and mp4 files

### ISSUE THREAD

**Issue by eminsr** [Nyx0uf/qlMoviePreview#3]
I want to know if there is a way that this plug-in could be disabled for mov, mp4 like formats because OS X supports those video files and plays them in Quicklook and I like to keep that feature. But formats like mkv and avi this plug-in best thing we got and for that thank you.

**Comment by Nyx0uf** [comment]
Should be possible by editing the .plist and the `+(BOOL)isValidFilepath:(NSString*)filepath`method. But I won't because I don't like the default OS X behaviour.

**Comment by eminsr** [comment]
Thank you for reply but there is an issue that I can't fix. I was trying to exclude some formats from qlMoviePreview and I did what you suggested. Now It says 'libavformat/a format.h' file not found. But I can see libavformat.a file under frameworks folder. So what would you suggest me to do? I would really appreciate your help. 

iPhone'umdan gönderildi

26 Eki 2015 tarihinde 11:23 saatinde, Nyx0uf <notifications@github.com> şunları yazdı:
