### ISSUE TITLE
Duration

### ISSUE THREAD

**Issue by eminsr** [Nyx0uf/qlMoviePreview#4]
![mediainfo_and_downloads](https://cloud.githubusercontent.com/assets/15310365/10818285/154c3402-7e49-11e5-908b-8268f3644735.png)
![screen shot 2015-10-29 at 15 23 17](https://cloud.githubusercontent.com/assets/15310365/10818286/15516e86-7e49-11e5-8ce7-dc38f6df39df.png)

Well as you can see duration information is not correct. It shows every file 1 hour more than it is.

**Comment by Nyx0uf** [comment]
I have lots of small videos files, can't reproduce. It's probably a FFMPEG bug.

**Comment by ParadiseDS** [comment]
same problem here. And bit depth info seems to be wrong too. I'm on macOS Sierra 10.12.2
I've upgrade ffmpeg to the latest version and manually rebuild the `qlMoviePreview.qlgenerator` , but it doesn't helps. I think there may be some problem with parsing the results returned by ffmpeg. All the durations here are 7 hours longer.

**Comment by Nyx0uf** [comment]
I suggest you use https://github.com/Marginal/QLVideo because I won't update this project.

**Comment by ParadiseDS** [comment]
I’ve tried that one but to myself the utilities of your work is more useful. I’ve reviewed some of the code in metadata parsing and may have found the problem. This plugin now works well here. However, as I’m totally a fresh in Mac as well as apple development, I’ll do more test to verify it. Maybe I’ll open a pull request for this plugin and maintain it myself.
Thanks for your work!

**Comment by ParadiseDS** [comment]
Thanks to fix the issue.
Exactly as the point I found.
